[manifest]
id = "de_v10lator_libbanio"
version = "0.1.1"
display_name = "I/O library"
description =  "An I/O library for Banjo: Recompiled"
short_description =  "An I/O library for Banjo: Recompiled"
authors = [ "V10lator" ]
game_id = "bk"
minimum_recomp_version = "1.0.1"
native_libraries = [
    { name = "libbanio", funcs = [ "libbanio_api" ] }
]

# Inputs to the mod tool.
[inputs]
elf_path = "build/mod.elf"
mod_filename = "libbanio"
func_reference_syms_file = "BanjoRecompSyms/bk.us.rev0.syms.toml"
data_reference_syms_files = [ "BanjoRecompSyms/bk.us.rev0.datasyms.toml" ]
additional_files = [ ]
